.gitignore, examples/flask/hello.py, examples/readme.md, moesifwsgi/middleware.py
Fix - Include milliseconds in the request and response time
Update - examples/flask/ initialize middleware before running the app
Update - examples/readme
Update - .gitignore
=> Fix - Include milliseconds in the request and response time

README.md, examples/bottle/hello.py, examples/flask/hello.py, moesifwsgi/middleware.py, requirements.txt, setup.py
Add: Option to capture outgoing requests
Update: Flask and Botle example
Update: README
Bump: version to 1.1.5
=> Add: Option to capture outgoing requests

requirements.txt
Refactor: Install specific library version
=> Refactor: Install specific library version

moesifwsgi/middleware.py, setup.py
Add: Sampling Events Flag
Bump version to 1.1.7
=> Add: Sampling Events Flag

moesifwsgi/middleware.py
It was not working with python3 (docs says another thing) but now it does. Tested with Python 3.6.
=> Python 3 fix

moesifwsgi/middleware.py, setup.py
Refactor: logic to fetch sample rate
=> Refactor: logic to fetch sample rate

requirements.txt, setup.py
Refactor: Update Dependencies
Bump version to 1.1.11
=> Refactor: Update Dependencies

README.md, moesifwsgi/middleware.py, setup.py
Add: Transaction Id to Request-Response Headers
Refactor: README.md
Bump version to 1.1.12
=> Add: Transaction Id to Request-Response Headers

moesifwsgi/middleware.py, setup.py
Fix: get client ip address
Bump version to 1.1.13
=> Fix: get client ip address

moesifwsgi/middleware.py, setup.py
Fix: Remove Client Ip headers encoding
Bump version to 1.1.14
=> Fix: Remove Client Ip headers encoding

README.md, moesifwsgi/middleware.py, moesifwsgi/update_companies.py, moesifwsgi/update_users.py, setup.py
Add: Capture Request URL Scheme
Add: Update company and batch companies functions
Refactor: Update User functions
Update: README.md
Bump version to 1.1.15
=> Add: Capture Request URL Scheme

README.md, moesifwsgi/middleware.py, setup.py
Add: CompanyId to EventModel
Update: README.md
Bump version to 1.1.18
=> Add: CompanyId to EventModel

README.md, requirements.txt
Update: moesifpythonrequest dependency to 0.1.9
Update: README.md
=> Update: moesifpythonrequest dependency to 0.1.9

README.md, moesifwsgi/middleware.py, requirements.txt, setup.py
Add: LogBody configuration option to remove request and response body
Update: moesifpythonrequest dependency to 0.1.10
Update: README.md
Bump version to 1.1.19
=> Add: LogBody configuration option to remove request and response body

moesifwsgi/app_config.py, moesifwsgi/client_ip.py, moesifwsgi/middleware.py, requirements.txt, setup.py
Refactor: Application Configuration
Add: Logic to fetch User/Company Sampling percentage
Refactor: Decode base64 encoded body
Refactor: Fetching ClientIp address
Bump moesifpythonrequest to 0.1.11
Bump version to 1.1.20
=> Refactor: Application Configuration

moesifwsgi/middleware.py, setup.py
Fix: Reset Input Strem to Byte for Python3
Bump version to 1.1.22
=> Fix: Reset Input Strem to Byte for Python3

examples/falcon/hello.py, examples/readme.md, moesifwsgi/middleware.py, setup.py
Fix: Base64 encoding when body contains non-ascii characters
Add: Example of Falcon web framework with Moesif Integrated
Bump version to 1.2.1
=> Fix: Base64 encoding when body contains non-ascii characters

README.md, requirements.txt, setup.py
Refactor: Update moesifapi version to 1.2.8
Refactor: Update README.md
Bump version to 1.2.2
=> Refactor: Update moesifapi version to 1.2.8

requirements.txt, setup.py
Refactor: Update moesifapi version to 1.3.0
Bump version to 1.2.3
=> Refactor: Update moesifapi version to 1.3.0

moesifwsgi/middleware.py, requirements.txt, setup.py
Add: direction and weight field to event
Refactor: Debug message
Refactor: Update moesifapi dependency to 1.3.2
Refactor: Update moesifpythonrequest dependency to 0.2.0
Bump version to 1.2.4
=> Add: direction and weight field to event

README.md, examples/bottle/hello.py, examples/flask/hello.py
Add: Endpoint to update User and company in examples
Refactor: Update README.md
=> Add: Endpoint to update User and company in examples

moesifwsgi/middleware.py, setup.py
Add: Support for gzip body
Bump version to 1.2.5
=> Add: Support for gzip body

moesifwsgi/app_config.py, setup.py
Add: Catch exception while getting application config
Refactor: Check if config is not empty before fetching
Bump version to 1.2.6
=> Add: Catch exception while getting application config

LICENSE, examples/bottle/requirements.txt, examples/falcon/requirements.txt, examples/flask/requirements.txt, examples/readme.md, moesifwsgi/app_config.py, moesifwsgi/event_mapper.py, moesifwsgi/logger_helper.py, moesifwsgi/middleware.py, moesifwsgi/moesif_data_holder.py, moesifwsgi/parse_body.py, moesifwsgi/send_async_event.py, moesifwsgi/send_batch_events.py, setup.py
Add: Support for batching/queuing events
Add: Helper functions
Add: Requirements.txt for examples
Refactor: Examples README.md
Refactor: License
Refactor: Add apscheduler as install requires the package
Bump version to 1.3.0
=> Add: Support for batching/queuing events

moesifwsgi/logger_helper.py, moesifwsgi/middleware.py, setup.py
Fix: Return event model if config not provided
Add: Checks before adding field to object
Bump version to 1.3.1
=> Fix: Return event model if config not provided

README.md
=> Refactor: Update REAMDE.md

README.md, moesifwsgi/app_config.py, moesifwsgi/client_ip.py, moesifwsgi/event_mapper.py, moesifwsgi/logger_helper.py, moesifwsgi/parse_body.py, moesifwsgi/send_batch_events.py, moesifwsgi/update_companies.py, moesifwsgi/update_users.py, setup.py
Add: Support to fetch user Id from authorization header
Refactor: Add Init method to the class
Refactor: Add Classmethod to the function who doesn't need class instance
Refactor: Update README.md
Bump version to 1.3.2
=> Add: Support to fetch user Id from authorization header

moesifwsgi/middleware.py, moesifwsgi/send_batch_events.py, setup.py
Refactor: Scheduler job for every worker
Refactor: Schedule events batch job every 2 second
Refactor: Avoid passing scheduler logging message to the ancestor loggers
Bump version to 1.3.4
=> Refactor: Scheduler job for every worker

moesifwsgi/middleware.py, setup.py
Add: BASE_URI config option
Bump version to 1.3.5
=> Add: BASE_URI config option

README.md
Refactor: Add MoesifProxy BaseURI to documentation
=> Refactor: Add MoesifProxy BaseURI to documentation

README.md
Refactor: Add Troubleshooting section in README
=> Refactor: Add Troubleshooting section in README

moesifwsgi/app_config.py, setup.py
=> Fix for config, if it has not been set or response returns empty body for config.

examples/bottle/requirements.txt, examples/falcon/requirements.txt, examples/flask/requirements.txt, moesifwsgi/middleware.py, moesifwsgi/moesif_data_holder.py, setup.py
Issue: https://github.com/Moesif/moesifasgi/issues/12
Ticket # 183381816
=> fixed incorrect elapsed time duration, and bump up version

moesifwsgi/event_mapper.py, moesifwsgi/http_response_catcher.py, moesifwsgi/logger_helper.py, moesifwsgi/middleware.py, moesifwsgi/moesif_data_holder.py, moesifwsgi/send_batch_events.py, moesifwsgi/update_companies.py, moesifwsgi/update_users.py, setup.py
Add: ProcessId to the logs and response header
Bump version to 1.6.1
=> Add: ProcessId to the logs and response header

requirements.txt, setup.py
https://www.pivotaltracker.com/story/show/184982077
=> Dependency fix and version bump to 1.7.0

README.md, moesifwsgi/logger_helper.py, moesifwsgi/middleware.py, setup.py
Add: Request body, Response body, and Response headers to environ 
Refactor: Update README.md
Bump version to 1.8.1
=> Add: Request body, Response body, and Response headers to environ

moesifwsgi/middleware.py, setup.py
Add: Log event model when debug is enabled
Bump version to 1.8.2
=> #185549282 Add: Log event model when debug is enabled

moesifwsgi/governance_manager.py
Refactor: Check for body of type dict in governance rule
=> #185629831 : Refactor: Check for body of type dict in governance rule

moesifwsgi/config_manager.py, moesifwsgi/middleware.py, moesifwsgi/workers.py, requirements.txt, setup.py
Add: Periodically fetch app config
Bump version to 1.9.1
=> #185629831 Add: Periodically fetch app config

requirements.txt, setup.py
Refactor: Bump moesifpythonrequest to version 0.3.2 
Bump version to 1.9.2
=> #186450397 Refactor: Bump moesifpythonrequest to version 0.3.2

moesifwsgi/middleware.py, setup.py
Refactor: Allow BaseUri to be set without depending on debug mode
Refactor: Bump version to 1.9.3
=> Refactor: Allow BaseUri to be set without depending on debug mode

moesifwsgi/middleware.py, requirements.txt, setup.py
Refactor: Bump moesifapi-python to version 1.4.9
Fix: Initialize capture outgoing requests
Bump version to 1.9.5
=> #188069117 Refactor: Bump moesifapi-python to version 1.4.9

moesifwsgi/middleware.py, setup.py
Refactor: Bump version to 1.10.2
=> DEV-7366 Refactor: Bump version to 1.10.2

moesifwsgi/middleware.py, setup.py
Refactor: Bump version to 1.10.3
=> DEV-7366 Refactor: Bump version to 1.10.3
